[package]
name = "smp-client"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
mcumgr-toolkit.workspace = true
sha2.workspace = true
tracing.workspace = true
transport = { path = "../transport" }

[dev-dependencies]
base64.workspace = true
serialport.workspace = true
smp-mock = { path = "../smp-mock" }
tracing-subscriber.workspace = true
